title:            Josh Corbett
email:            joshwcorbett@icloud.com
description:      Josh Corbett is a Graphics and Web Designer / Developer in Montana's Flathead Valley. He likes to work with local and remote businesses to help them stand out from the craziness that is the world wide web.
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "https://joshcorbett.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  joshwcorbett

# 0: Open to Projects
# 1: Busy with Existing Projects
project_status: 0

# Social Media
instagram_followers: 25K
linkedin_followers:  41
dribbble_followers:  51

# Build settings
markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

plugins:
  - jekyll-feed
  - sprockets-sass
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-autoprefixer
  - jekyll-commonmark
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /project/:title
  articles:
    output: true
    pemalink: /article/:title

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: post
  - scope:
      path: ""
      type: "articles"
    values:
      layout: post

sass:
  sass_dir: assets/css/
  style: compressed

jekyll_admin:
  hidden_links:
    - posts

exclude:
  - .jekyll-cache

incremental: true